package top.zhangsun.bean.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.zhangsun.bean.pojo.entity.ActivityEntity;
import top.zhangsun.bean.pojo.entity.ActivityEntityExample;

public interface ActivityEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY
     *
     * @mbg.generated
     */
    long countByExample(ActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY
     *
     * @mbg.generated
     */
    int deleteByExample(ActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY
     *
     * @mbg.generated
     */
    int insert(ActivityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY
     *
     * @mbg.generated
     */
    int insertSelective(ActivityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY
     *
     * @mbg.generated
     */
    List<ActivityEntity> selectByExample(ActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY
     *
     * @mbg.generated
     */
    ActivityEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ActivityEntity record, @Param("example") ActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ActivityEntity record, @Param("example") ActivityEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActivityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActivityEntity record);
}