package top.zhangsun.bean.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.zhangsun.bean.pojo.entity.ActivityTypeEntity;
import top.zhangsun.bean.pojo.entity.ActivityTypeEntityExample;

public interface ActivityTypeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY_TYPE
     *
     * @mbg.generated
     */
    long countByExample(ActivityTypeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY_TYPE
     *
     * @mbg.generated
     */
    int deleteByExample(ActivityTypeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY_TYPE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY_TYPE
     *
     * @mbg.generated
     */
    int insert(ActivityTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY_TYPE
     *
     * @mbg.generated
     */
    int insertSelective(ActivityTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY_TYPE
     *
     * @mbg.generated
     */
    List<ActivityTypeEntity> selectByExample(ActivityTypeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY_TYPE
     *
     * @mbg.generated
     */
    ActivityTypeEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY_TYPE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ActivityTypeEntity record, @Param("example") ActivityTypeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY_TYPE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ActivityTypeEntity record, @Param("example") ActivityTypeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY_TYPE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActivityTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_ACTIVITY_TYPE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActivityTypeEntity record);
}