package top.zhangsun.bean.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.zhangsun.bean.pojo.entity.Bean;
import top.zhangsun.bean.pojo.entity.BeanExample;

public interface BeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    long countByExample(BeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int deleteByExample(BeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int insert(Bean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int insertSelective(Bean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    List<Bean> selectByExample(BeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    Bean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Bean record, @Param("example") BeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Bean record, @Param("example") BeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Bean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Bean record);
}