package top.zhangsun.bean.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.zhangsun.bean.pojo.entity.BeanEntity;
import top.zhangsun.bean.pojo.entity.BeanEntityExample;

public interface BeanEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    long countByExample(BeanEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int deleteByExample(BeanEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int insert(BeanEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int insertSelective(BeanEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    List<BeanEntity> selectByExample(BeanEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    BeanEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BeanEntity record, @Param("example") BeanEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BeanEntity record, @Param("example") BeanEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BeanEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_BEAN
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BeanEntity record);
}