package top.zhangsun.bean.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.zhangsun.bean.pojo.entity.UserEntity;
import top.zhangsun.bean.pojo.entity.UserEntityExample;

public interface UserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_USER
     *
     * @mbg.generated
     */
    long countByExample(UserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_USER
     *
     * @mbg.generated
     */
    int deleteByExample(UserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_USER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_USER
     *
     * @mbg.generated
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_USER
     *
     * @mbg.generated
     */
    int insertSelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_USER
     *
     * @mbg.generated
     */
    List<UserEntity> selectByExample(UserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_USER
     *
     * @mbg.generated
     */
    UserEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_USER
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserEntity record, @Param("example") UserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_USER
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserEntity record, @Param("example") UserEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHINA_SOFT_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserEntity record);
}