package top.zhangsun.bean.pojo.entity;

import java.util.Date;

public class ActivityEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.bean
     *
     * @mbg.generated
     */
    private Integer bean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.bean_total
     *
     * @mbg.generated
     */
    private Integer beanTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.publisher
     *
     * @mbg.generated
     */
    private Integer publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.boss
     *
     * @mbg.generated
     */
    private Integer boss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_ACTIVITY.delete_flag
     *
     * @mbg.generated
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.id
     *
     * @return the value of CHINA_SOFT_ACTIVITY.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.id
     *
     * @param id the value for CHINA_SOFT_ACTIVITY.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.title
     *
     * @return the value of CHINA_SOFT_ACTIVITY.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.title
     *
     * @param title the value for CHINA_SOFT_ACTIVITY.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.description
     *
     * @return the value of CHINA_SOFT_ACTIVITY.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.description
     *
     * @param description the value for CHINA_SOFT_ACTIVITY.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.type
     *
     * @return the value of CHINA_SOFT_ACTIVITY.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.type
     *
     * @param type the value for CHINA_SOFT_ACTIVITY.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.bean
     *
     * @return the value of CHINA_SOFT_ACTIVITY.bean
     *
     * @mbg.generated
     */
    public Integer getBean() {
        return bean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.bean
     *
     * @param bean the value for CHINA_SOFT_ACTIVITY.bean
     *
     * @mbg.generated
     */
    public void setBean(Integer bean) {
        this.bean = bean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.bean_total
     *
     * @return the value of CHINA_SOFT_ACTIVITY.bean_total
     *
     * @mbg.generated
     */
    public Integer getBeanTotal() {
        return beanTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.bean_total
     *
     * @param beanTotal the value for CHINA_SOFT_ACTIVITY.bean_total
     *
     * @mbg.generated
     */
    public void setBeanTotal(Integer beanTotal) {
        this.beanTotal = beanTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.start_time
     *
     * @return the value of CHINA_SOFT_ACTIVITY.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.start_time
     *
     * @param startTime the value for CHINA_SOFT_ACTIVITY.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.end_time
     *
     * @return the value of CHINA_SOFT_ACTIVITY.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.end_time
     *
     * @param endTime the value for CHINA_SOFT_ACTIVITY.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.publisher
     *
     * @return the value of CHINA_SOFT_ACTIVITY.publisher
     *
     * @mbg.generated
     */
    public Integer getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.publisher
     *
     * @param publisher the value for CHINA_SOFT_ACTIVITY.publisher
     *
     * @mbg.generated
     */
    public void setPublisher(Integer publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.boss
     *
     * @return the value of CHINA_SOFT_ACTIVITY.boss
     *
     * @mbg.generated
     */
    public Integer getBoss() {
        return boss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.boss
     *
     * @param boss the value for CHINA_SOFT_ACTIVITY.boss
     *
     * @mbg.generated
     */
    public void setBoss(Integer boss) {
        this.boss = boss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.create_time
     *
     * @return the value of CHINA_SOFT_ACTIVITY.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.create_time
     *
     * @param createTime the value for CHINA_SOFT_ACTIVITY.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.update_time
     *
     * @return the value of CHINA_SOFT_ACTIVITY.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.update_time
     *
     * @param updateTime the value for CHINA_SOFT_ACTIVITY.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_ACTIVITY.delete_flag
     *
     * @return the value of CHINA_SOFT_ACTIVITY.delete_flag
     *
     * @mbg.generated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_ACTIVITY.delete_flag
     *
     * @param deleteFlag the value for CHINA_SOFT_ACTIVITY.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}