package top.zhangsun.bean.pojo.entity;

import java.util.Date;

public class BeanEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_BEAN.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_BEAN.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_BEAN.rate
     *
     * @mbg.generated
     */
    private Double rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_BEAN.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_BEAN.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_BEAN.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_BEAN.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_BEAN.delete_flag
     *
     * @mbg.generated
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_BEAN.id
     *
     * @return the value of CHINA_SOFT_BEAN.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_BEAN.id
     *
     * @param id the value for CHINA_SOFT_BEAN.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_BEAN.name
     *
     * @return the value of CHINA_SOFT_BEAN.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_BEAN.name
     *
     * @param name the value for CHINA_SOFT_BEAN.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_BEAN.rate
     *
     * @return the value of CHINA_SOFT_BEAN.rate
     *
     * @mbg.generated
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_BEAN.rate
     *
     * @param rate the value for CHINA_SOFT_BEAN.rate
     *
     * @mbg.generated
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_BEAN.logo
     *
     * @return the value of CHINA_SOFT_BEAN.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_BEAN.logo
     *
     * @param logo the value for CHINA_SOFT_BEAN.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_BEAN.currency
     *
     * @return the value of CHINA_SOFT_BEAN.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_BEAN.currency
     *
     * @param currency the value for CHINA_SOFT_BEAN.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_BEAN.create_time
     *
     * @return the value of CHINA_SOFT_BEAN.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_BEAN.create_time
     *
     * @param createTime the value for CHINA_SOFT_BEAN.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_BEAN.update_time
     *
     * @return the value of CHINA_SOFT_BEAN.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_BEAN.update_time
     *
     * @param updateTime the value for CHINA_SOFT_BEAN.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_BEAN.delete_flag
     *
     * @return the value of CHINA_SOFT_BEAN.delete_flag
     *
     * @mbg.generated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_BEAN.delete_flag
     *
     * @param deleteFlag the value for CHINA_SOFT_BEAN.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}