package top.zhangsun.bean.pojo.entity;

import java.util.Date;

public class UserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_USER.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_USER.name_chinese
     *
     * @mbg.generated
     */
    private String nameChinese;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_USER.name_english
     *
     * @mbg.generated
     */
    private String nameEnglish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_USER.e_id
     *
     * @mbg.generated
     */
    private String eId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_USER.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_USER.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_USER.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHINA_SOFT_USER.delete
     *
     * @mbg.generated
     */
    private Boolean delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_USER.id
     *
     * @return the value of CHINA_SOFT_USER.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_USER.id
     *
     * @param id the value for CHINA_SOFT_USER.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_USER.name_chinese
     *
     * @return the value of CHINA_SOFT_USER.name_chinese
     *
     * @mbg.generated
     */
    public String getNameChinese() {
        return nameChinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_USER.name_chinese
     *
     * @param nameChinese the value for CHINA_SOFT_USER.name_chinese
     *
     * @mbg.generated
     */
    public void setNameChinese(String nameChinese) {
        this.nameChinese = nameChinese == null ? null : nameChinese.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_USER.name_english
     *
     * @return the value of CHINA_SOFT_USER.name_english
     *
     * @mbg.generated
     */
    public String getNameEnglish() {
        return nameEnglish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_USER.name_english
     *
     * @param nameEnglish the value for CHINA_SOFT_USER.name_english
     *
     * @mbg.generated
     */
    public void setNameEnglish(String nameEnglish) {
        this.nameEnglish = nameEnglish == null ? null : nameEnglish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_USER.e_id
     *
     * @return the value of CHINA_SOFT_USER.e_id
     *
     * @mbg.generated
     */
    public String geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_USER.e_id
     *
     * @param eId the value for CHINA_SOFT_USER.e_id
     *
     * @mbg.generated
     */
    public void seteId(String eId) {
        this.eId = eId == null ? null : eId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_USER.open_id
     *
     * @return the value of CHINA_SOFT_USER.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_USER.open_id
     *
     * @param openId the value for CHINA_SOFT_USER.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_USER.create_time
     *
     * @return the value of CHINA_SOFT_USER.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_USER.create_time
     *
     * @param createTime the value for CHINA_SOFT_USER.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_USER.update_time
     *
     * @return the value of CHINA_SOFT_USER.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_USER.update_time
     *
     * @param updateTime the value for CHINA_SOFT_USER.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHINA_SOFT_USER.delete
     *
     * @return the value of CHINA_SOFT_USER.delete
     *
     * @mbg.generated
     */
    public Boolean getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHINA_SOFT_USER.delete
     *
     * @param delete the value for CHINA_SOFT_USER.delete
     *
     * @mbg.generated
     */
    public void setDelete(Boolean delete) {
        this.delete = delete;
    }
}